# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #VM WORDPRESS
  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "ubuntu/focal64"
    wordpress.vm.box_check_update = false
    wordpress.vm.hostname = "wordpress"
    wordpress.vm.provision "shell", path: "discowp.sh"
    wordpress.vm.provision "shell", path: "provisionwp.sh"
    wordpress.vm.network "private_network", ip: "192.168.0.2", virtualbox__intnet: "keepcoding"
    wordpress.vm.network "forwarded_port", guest: 80 , host: 8081
    wordpress.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      file_to_disk = "wpextradisk1.vmdk"
      unless File.exist?(file_to_disk)
        v.customize [ "createmedium", "disk", "--filename", file_to_disk, "--format", "vmdk", "--size", 8096 * 1 ]
      end
      v.customize [ "storageattach", :id, "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
  end

  #VM ELASTICSEARCH
  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.box = "ubuntu/focal64"
    elasticsearch.vm.box_check_update = false
    elasticsearch.vm.provision "shell", path: "discoelk.sh"
    elasticsearch.vm.provision "shell", path: "provisionelk.sh"
    elasticsearch.vm.hostname = "elasticsearch"
    elasticsearch.vm.network "private_network", ip: "192.168.0.3", virtualbox__intnet: "keepcoding"
    elasticsearch.vm.network "forwarded_port", guest: 9200, host: 9200
    elasticsearch.vm.network "forwarded_port", guest: 80 , host: 8080
    elasticsearch.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 1
      file_to_disk = "elkextradisk1.vmdk"
      unless File.exist?(file_to_disk)
        v.customize [ "createmedium", "disk", "--filename", file_to_disk, "--format", "vmdk", "--size", 8096 * 1 ]
      end
      v.customize [ "storageattach", :id, "--storagectl", "SCSI", "--port", "2", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end
  end

end
